logging:
  level:
    org.springframework.security: TRACE
    io.kafbat.ui.service.rbac: TRACE

dynamic.config.enabled: true

server:
  port: 9090 # prevent clashes with keycloak ports

auth:
  type: OAUTH2
  oauth2:
    client:
      keycloak:
        clientId: kafbat-ui-client
        clientSecret: # CLIENT SECRET OBTAINED FROM KEYCLOAK
        scope: openid,roles
        client-name: keycloak
        provider: keycloak
        redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
        authorization-grant-type: authorization_code
        issuer-uri: http://localhost:8080/realms/myrealm
        user-name-attribute: name
        custom-params:
          type: oauth
          roles-field: groups

rbac:
  roles:
    - name: "admins"
      clusters:
        - local
      subjects:
        - provider: oauth
          type: role
          value: "ops"

      permissions:
        - resource: applicationconfig
          actions: all

        - resource: clusterconfig
          actions: all

        - resource: topic
          value: ".*"
          actions: all

        - resource: consumer
          value: ".*"
          actions: all

        - resource: schema
          value: ".*"
          actions: all

        - resource: connect
          value: ".*"
          actions: all

        - resource: ksql
          actions: all

        - resource: acl
          actions: all

        - resource: audit
          actions: all
    - name: "readonly"
      clusters:
        - local
      subjects:
        - provider: oauth
          type: role
          value: "ronly"
      permissions:
        - resource: clusterconfig
          actions: [ "view" ]

        - resource: topic
          value: ".*"
          actions:
            - VIEW
            - MESSAGES_READ

        - resource: consumer
          value: ".*"
          actions: [ view ]

        - resource: schema
          value: ".*"
          actions: [ view ]

        - resource: connect
          value: ".*"
          actions: [ view ]

        - resource: acl
          actions: [ view ]
